CREATE TABLE IF NOT EXISTS HRUSER (
    USER_ID VARCHAR(20) PRIMARY KEY,
    PWD VARCHAR(100) NOT NULL,
    HECNAME NVARCHAR(50) NOT NULL,
    ROLE VARCHAR(10) NOT NULL,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    EMAIL VARCHAR(100),
    LAST_LOGIN_TIME DATETIME NULL,
    LOGIN_FAIL_COUNT INT DEFAULT 0,
    IS_LOCKED BOOLEAN DEFAULT FALSE,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL,
    ID_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS NVARCHAR(100),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_NO VARCHAR(20) PRIMARY KEY,
    USER_ID VARCHAR(20) NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    OPEN_DATE DATETIME NOT NULL,
    CLOSE_DATE DATETIME NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACCOUNTS_USER FOREIGN KEY (USER_ID) REFERENCES HRUSER(USER_ID),
    CONSTRAINT FK_ACCOUNTS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS TXNRECS (
    TXN_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_NO VARCHAR(20) NOT NULL,
    RELATED_ACC_NO VARCHAR(20),
    TXN_TYPE VARCHAR(10) NOT NULL,
    TXN_AMOUNT DECIMAL(18,2) NOT NULL,
    TXN_TIME DATETIME NOT NULL,
    TXN_STATUS VARCHAR(10) NOT NULL,
    NOTE NVARCHAR(100),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_TXNRECS_ACCOUNT FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO),
    CONSTRAINT FK_TXNRECS_RELATED_ACCOUNT FOREIGN KEY (RELATED_ACC_NO) REFERENCES ACCOUNTS(ACCOUNT_NO)
);

CREATE TABLE IF NOT EXISTS REVIEWS (
    REVIEW_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(20) NOT NULL,
    TARGET_ID VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    REVIEWER VARCHAR(20) NOT NULL,
    REVIEW_TIME DATETIME NULL,
    REASON NVARCHAR(100),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_REVIEWS_REVIEWER FOREIGN KEY (REVIEWER) REFERENCES HRUSER(USER_ID)
);

CREATE TABLE IF NOT EXISTS SETTINGS (
    SETTING_KEY VARCHAR(50) PRIMARY KEY,
    SETTING_VALUE VARCHAR(100) NOT NULL,
    DESCRIPTION NVARCHAR(100),
    IS_EDITABLE BOOLEAN DEFAULT TRUE,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
